# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt; fi
    - name: Update html with new
      run: |
        python code/configuration.py
        git config --global user.name 'Roberbg97'
        git config --global user.email roberbg97@gmail.com
        git add .
        git commit --allow-empty -am "Updated HTML"
        git push

