# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      UPDATED: 0

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Cache pip
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Update env var
      uses: allenevans/set-env@v1.0.0
        with:
          UPDATED: $(python -c "import os;print(open('UPDATED').read());os.remove('UPDATED')")
    - name: Update html with new
      if: ${{env.UPDATED==0}}
      run: |
        python code/configuration.py
        git config --global user.name 'Roberbg97'
        git config --global user.email roberbg97@gmail.com
        git add .
        git commit --allow-empty -am "Updated HTML"
        git push

